// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ufhqeabyubosesdtlqbw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVmaHFlYWJ5dWJvc2VzZHRscWJ3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkzODQ3OTMsImV4cCI6MjA2NDk2MDc5M30.8fp5fvgUwltvjtAMA98Odqu1X6hRqj-r5WUDI5uQr0o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);